---
- name: Rulebook de monitoreo de alertas
  hosts: all
  sources:
    - name: webhook
      ansible.eda.webhook:
        hosts: 0.0.0.0
        port: 6666

  rules:
    - name: Newrelic | Alerta FS lleno /terraform
      condition: event.payload.sources == "newrelic"
      action:
        run_workflow_template:
          name: "WF_Limpieza_fs"
          organization: "Desarrollo"
          job_args:
            extra_vars:
              servidor: "{{ event.payload.hostname }}"
              fs: "{{ event.payload.filesystem }}"
...
