---
- name: Test1
  hosts: all
  sources:
    - name: Test
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 6666
  rules:
    - name: regla fs
      condition: event.payload.message == "test01"
      action:
        run_job_template:
          name: "Demo test"
          organization: "Desarrollo"
          job_args:
            extra_vars:
              nombre: "John"
...
