---
- name: Remediar limpieza fs Terraform
  hosts: "{{ servidor }}"
  gather_facts: false
  tasks:

  - name: Eliminar archivo
    file:
      path: "{{ fs  ~ '/testfile' }}"
      state: absent
...
